#!/usr/bin/env bash
# Regenerate langfuse/.env with fresh random secrets, keeping the coupled
# vars (POSTGRES_PASSWORD <-> DATABASE_URL, MINIO_ROOT_PASSWORD <-> the
# three S3 secret keys) consistent, and sync the project API keys into the
# root .env that agent/tracing.py actually reads.
#
# Usage (run from the repo root, e.g. ~/work/Agentic_platform):
#   bash generate_langfuse_env.sh
#
# Re-running this on an existing setup will invalidate any data already
# provisioned in the Postgres/ClickHouse/MinIO volumes -- follow it with:
#   cd langfuse && docker compose down -v && docker compose up -d

set -euo pipefail

LANGFUSE_ENV="langfuse/.env"
ROOT_ENV=".env"

if [[ ! -d "langfuse" ]]; then
  echo "Error: no langfuse/ directory here. Run this from the repo root." >&2
  exit 1
fi

hex32() { openssl rand -hex 32; }   # 64 hex chars, for ENCRYPTION_KEY
hex16() { openssl rand -hex 16; }   # 32 hex chars, for passwords/secrets

# Prefer uuidgen; fall back to python3 if it's not installed.
gen_uuid() {
  if command -v uuidgen >/dev/null 2>&1; then
    uuidgen
  else
    python3 -c "import uuid; print(uuid.uuid4())"
  fi
}

POSTGRES_PASSWORD="$(hex16)"
CLICKHOUSE_PASSWORD="$(hex16)"
MINIO_ROOT_PASSWORD="$(hex16)"
REDIS_AUTH="$(hex16)"
SALT="$(hex16)"
ENCRYPTION_KEY="$(hex32)"
NEXTAUTH_SECRET="$(hex16)"
INIT_USER_PASSWORD="$(hex16)"
PROJECT_PUBLIC_KEY="pk-lf-$(gen_uuid)"
PROJECT_SECRET_KEY="sk-lf-$(gen_uuid)"

# Customize these if your org/project/user identifiers should differ.
ORG_ID="agentic-platform"
ORG_NAME="Agentic Platform POC"
PROJECT_ID="agentic-platform-poc"
PROJECT_NAME="Agentic Platform POC"
USER_EMAIL="admin@example.com"
USER_NAME="Admin"

if [[ -f "$LANGFUSE_ENV" ]]; then
  backup="${LANGFUSE_ENV}.bak.$(date +%Y%m%dT%H%M%S)"
  cp "$LANGFUSE_ENV" "$backup"
  echo "Backed up existing $LANGFUSE_ENV -> $backup"
fi

cat > "$LANGFUSE_ENV" <<EOF
# Generated by generate_langfuse_env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# .env itself is gitignored -- only langfuse/.env.example is version controlled.

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
REDIS_AUTH=${REDIS_AUTH}
SALT=${SALT}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# The compose file's DATABASE_URL/S3 key defaults don't auto-pick-up the
# POSTGRES_PASSWORD/MINIO_ROOT_PASSWORD above -- they're repeated here,
# generated to match.
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
MINIO_ROOT_USER=minio
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=minio
LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}

# Auto-provisioned on first boot so the agent has stable API keys without a
# manual UI setup step.
LANGFUSE_INIT_ORG_ID=${ORG_ID}
LANGFUSE_INIT_ORG_NAME=${ORG_NAME}
LANGFUSE_INIT_PROJECT_ID=${PROJECT_ID}
LANGFUSE_INIT_PROJECT_NAME=${PROJECT_NAME}
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${PROJECT_PUBLIC_KEY}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${PROJECT_SECRET_KEY}
LANGFUSE_INIT_USER_EMAIL=${USER_EMAIL}
LANGFUSE_INIT_USER_NAME=${USER_NAME}
LANGFUSE_INIT_USER_PASSWORD=${INIT_USER_PASSWORD}
EOF

chmod 600 "$LANGFUSE_ENV"
echo "Wrote $LANGFUSE_ENV (permissions set to 600)"

# Sync the project keys into the root .env that agent/tracing.py reads.
if [[ -f "$ROOT_ENV" ]]; then
  backup_root="${ROOT_ENV}.bak.$(date +%Y%m%dT%H%M%S)"
  cp "$ROOT_ENV" "$backup_root"
  echo "Backed up existing $ROOT_ENV -> $backup_root"

  if grep -q '^LANGFUSE_PUBLIC_KEY=' "$ROOT_ENV"; then
    sed -i "s|^LANGFUSE_PUBLIC_KEY=.*|LANGFUSE_PUBLIC_KEY=${PROJECT_PUBLIC_KEY}|" "$ROOT_ENV"
  else
    echo "LANGFUSE_PUBLIC_KEY=${PROJECT_PUBLIC_KEY}" >> "$ROOT_ENV"
  fi

  if grep -q '^LANGFUSE_SECRET_KEY=' "$ROOT_ENV"; then
    sed -i "s|^LANGFUSE_SECRET_KEY=.*|LANGFUSE_SECRET_KEY=${PROJECT_SECRET_KEY}|" "$ROOT_ENV"
  else
    echo "LANGFUSE_SECRET_KEY=${PROJECT_SECRET_KEY}" >> "$ROOT_ENV"
  fi
  chmod 600 "$ROOT_ENV"
  echo "Synced LANGFUSE_PUBLIC_KEY / LANGFUSE_SECRET_KEY into $ROOT_ENV"
else
  echo "No root .env found -- create one from .env.example, then re-run this script"
  echo "so it can sync LANGFUSE_PUBLIC_KEY/LANGFUSE_SECRET_KEY into it."
fi

cat <<'EOF'

Done. Since the Postgres/MinIO/ClickHouse volumes may already hold data
provisioned under old credentials, do a clean restart:

    cd langfuse
    docker compose down -v
    docker compose up -d
    docker compose ps          # confirm langfuse-web reaches "healthy"

EOF
