"""Deterministic tools the agent graph calls out to.

These wrap the HotSpot power trace, the part -> material -> simulation_run
knowledge graph (scripts/ingest_graph.py), and the Chroma datasheet
collection (scripts/ingest_pdfs.py). Kept separate from the LLM nodes so the
"facts" the executor grounds its draft in are computed deterministically,
not generated by the model.
"""

from pathlib import Path

import chromadb
import ollama
from langfuse import observe

from agent.config import EMBED_MODEL, RETRIEVAL_K
from agent.graph_db import run_query

REPO_ROOT = Path(__file__).resolve().parent.parent
HOTSPOT_DIR = REPO_ROOT / "data" / "hotspot_example1"
CHROMA_DIR = REPO_ROOT / "chroma_db"


@observe(name="tool.get_peak_power_unit", as_type="tool")
def get_peak_power_unit(ptrace_path: Path = HOTSPOT_DIR / "gcc.ptrace") -> dict:
    """Return the floorplan unit with the highest peak power draw across
    the trace, plus its peak and average power (in watts)."""
    lines = [line for line in ptrace_path.read_text().splitlines() if line.strip()]
    units = lines[0].split()
    rows = [[float(v) for v in line.split()] for line in lines[1:]]

    peak_unit, peak_value, peak_avg = None, float("-inf"), 0.0
    for col, unit in enumerate(units):
        values = [row[col] for row in rows]
        col_peak = max(values)
        if col_peak > peak_value:
            peak_unit, peak_value, peak_avg = unit, col_peak, sum(values) / len(values)

    return {"unit": peak_unit, "peak_power": peak_value, "avg_power": peak_avg, "n_samples": len(rows)}


@observe(name="tool.get_unit_material", as_type="tool")
def get_unit_material(unit: str, floorplan_id: str = "ev6") -> str | None:
    """Look up what material a floorplan unit is made of via the
    part -> material knowledge graph built by scripts/ingest_graph.py."""
    part_id = f"{floorplan_id}::{unit}"
    rows = run_query(
        "MATCH (:Part {id: $part_id})-[:MADE_OF]->(m:Material) RETURN m.id AS material LIMIT 1",
        part_id=part_id,
    )
    return rows[0]["material"] if rows else None


@observe(name="tool.retrieve_context", as_type="retriever")
def retrieve_context(query: str, k: int = RETRIEVAL_K, collection: str = "datasheets") -> list[dict]:
    """Semantic search over the ingested PDF datasheets/specs."""
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    col = client.get_collection(collection)
    embedding = ollama.embed(model=EMBED_MODEL, input=[query]).embeddings
    results = col.query(query_embeddings=embedding, n_results=k)
    return [
        {"source": meta["source"], "page": meta["page"], "text": doc}
        for doc, meta in zip(results["documents"][0], results["metadatas"][0])
    ]
