"""Deterministic tools the agent graph calls out to.

These wrap the HotSpot power trace, the part -> material -> simulation_run
knowledge graph (scripts/ingest_graph.py), and the Chroma datasheet
collection (scripts/ingest_pdfs.py). Kept separate from the LLM nodes so the
"facts" the executor grounds its draft in are computed deterministically,
not generated by the model.
"""

from pathlib import Path

import chromadb
import networkx as nx
import ollama

REPO_ROOT = Path(__file__).resolve().parent.parent
HOTSPOT_DIR = REPO_ROOT / "data" / "hotspot_example1"
GRAPH_PATH = REPO_ROOT / "graph" / "knowledge_graph.graphml"
CHROMA_DIR = REPO_ROOT / "chroma_db"
EMBED_MODEL = "nomic-embed-text"


def get_peak_power_unit(ptrace_path: Path = HOTSPOT_DIR / "gcc.ptrace") -> dict:
    """Return the floorplan unit with the highest peak power draw across
    the trace, plus its peak and average power (in watts)."""
    lines = [line for line in ptrace_path.read_text().splitlines() if line.strip()]
    units = lines[0].split()
    rows = [[float(v) for v in line.split()] for line in lines[1:]]

    peak_unit, peak_value, peak_avg = None, float("-inf"), 0.0
    for col, unit in enumerate(units):
        values = [row[col] for row in rows]
        col_peak = max(values)
        if col_peak > peak_value:
            peak_unit, peak_value, peak_avg = unit, col_peak, sum(values) / len(values)

    return {"unit": peak_unit, "peak_power": peak_value, "avg_power": peak_avg, "n_samples": len(rows)}


def get_unit_material(unit: str, floorplan_id: str = "ev6", graph_path: Path = GRAPH_PATH) -> str | None:
    """Look up what material a floorplan unit is made of via the
    part -> material knowledge graph built by scripts/ingest_graph.py."""
    graph = nx.read_graphml(graph_path)
    part_id = f"{floorplan_id}::{unit}"
    if part_id not in graph:
        return None
    for _, target, data in graph.out_edges(part_id, data=True):
        if data.get("relation") == "made_of":
            return target
    return None


def retrieve_context(query: str, k: int = 4, collection: str = "datasheets") -> list[dict]:
    """Semantic search over the ingested PDF datasheets/specs."""
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    col = client.get_collection(collection)
    embedding = ollama.embed(model=EMBED_MODEL, input=[query]).embeddings
    results = col.query(query_embeddings=embedding, n_results=k)
    return [
        {"source": meta["source"], "page": meta["page"], "text": doc}
        for doc, meta in zip(results["documents"][0], results["metadatas"][0])
    ]
